import { render, screen, waitFor, within } from "@testing-library/react";
import StudioShell from "@/components/StudioShell";
import { resetStore } from "./helpers";

beforeEach(resetStore);

describe("operator states", () => {
  it("shows project loading without fixture content", () => { vi.stubGlobal("fetch", vi.fn(() => new Promise(() => {}))); render(<StudioShell />); expect(screen.getByRole("status", { name: "Loading projects" })).toBeInTheDocument(); expect(screen.getByRole("region", { name: "Preview monitor" })).toHaveTextContent(/Loading real local projects/); expect(screen.queryByText(/Airbnb Cinematic/)).not.toBeInTheDocument(); });
  it("shows project API failure with Retry", async () => { vi.stubGlobal("fetch", vi.fn(async () => Response.json({ error: { code: "internal", message: "Unavailable" } }, { status: 500 }))); render(<StudioShell />); const nav=screen.getByRole("complementary", { name: "Project navigation" }); const alert=await within(nav).findByRole("alert"); expect(alert).toHaveTextContent(/Projects unavailable/); expect(within(alert).getByRole("button", { name: "Retry" })).toBeInTheDocument(); expect(screen.getByRole("region", { name: "Preview monitor" })).toHaveTextContent(/Projects could not be loaded[\s\S]*Retry in the Projects panel/); expect(screen.queryByText(/Mock preview/)).not.toBeInTheDocument(); });
  it("shows an honest no-project state", async () => { vi.stubGlobal("fetch", vi.fn(async () => Response.json({ schemaVersion: 1, projects: [] }))); render(<StudioShell />); const preview=screen.getByRole("region", { name: "Preview monitor" }); await waitFor(() => expect(preview).toHaveTextContent(/No materialized projects available/)); expect(preview).toHaveTextContent(/Source files remain safe/); expect(screen.queryByText(/Mock preview/)).not.toBeInTheDocument(); });
  it("shows an honest state when projects exist but none are preview-ready", async () => { vi.stubGlobal("fetch", vi.fn(async () => Response.json({ schemaVersion: 1, projects: [{ schemaVersion: 1, projectId: "demo", projectName: "Demo", clientSlug: null, previewReady: false, cacheTimestamp: null }] }))); render(<StudioShell />); const preview=screen.getByRole("region", { name: "Preview monitor" }); await waitFor(() => expect(preview).toHaveTextContent(/No preview-ready project is available/)); expect(preview).toHaveTextContent(/Materialize a project outside Studio/); expect(screen.queryByText(/Mock preview/)).not.toBeInTheDocument(); });
});
